name       : libvterm
version    : 0.1
release    : 1
source     :
    - https://github.com/neovim/libvterm/archive/a9c7c6fd20fa35e0ad3e0e98901ca12dfca9c25c.tar.gz : 1a4272be91d9614dc183a503786df83b6584e4afaab7feaaa5409f841afbd796
license    : MIT
summary    : Abstract library implementation of a VT220/xterm/ECMA-48 terminal emulator
description: |
    Abstract library implementation of a VT220/xterm/ECMA-48 terminal emulator
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
