name       : libvterm
version    : 0.1.4
release    : 3
source     :
    - http://www.leonerd.org.uk/code/libvterm/libvterm-0.1.4.tar.gz : bc70349e95559c667672fc8c55b9527d9db9ada0fb80a3beda533418d782d3dd
license    : MIT
component  : programming
summary    : Abstract library implementation of a VT220/xterm/ECMA-48 terminal emulator
description: |
    Abstract library implementation of a VT220/xterm/ECMA-48 terminal emulator
build      : |
    %make PREFIX=/usr LIBDIR=%libdir%
install    : |
    %make_install PREFIX=/usr LIBDIR=%libdir%
