name       : libvterm
version    : 0.1.2
release    : 2
source     :
    - http://www.leonerd.org.uk/code/libvterm/libvterm-0.1.2.tar.gz : 250899f434ff624a16d2be3784b5fe03f81820c3597211faf04349f5c9297f81
license    : MIT
component  : programming
summary    : Abstract library implementation of a VT220/xterm/ECMA-48 terminal emulator
description: |
    Abstract library implementation of a VT220/xterm/ECMA-48 terminal emulator
build      : |
    %make PREFIX=/usr LIBDIR=%libdir%
install    : |
    %make_install PREFIX=/usr LIBDIR=%libdir%
