name       : libvterm
version    : '0.3'
release    : 4
source     :
    - https://www.leonerd.org.uk/code/libvterm/libvterm-0.3.tar.gz : 61eb0d6628c52bdf02900dfd4468aa86a1a7125228bab8a67328981887483358
license    : MIT
component  : programming
summary    : Abstract library implementation of a VT220/xterm/ECMA-48 terminal emulator
description: |
    Abstract library implementation of a VT220/xterm/ECMA-48 terminal emulator
build      : |
    %make PREFIX=/usr LIBDIR=%libdir%
install    : |
    %make_install PREFIX=/usr LIBDIR=%libdir%
